config/routes.rb
Rails.application.routes.draw do
  resources :weapons
  get 'robot/index'
  get 'robot/new'
  get 'robot/edit'
  get 'robot/show'
  resources :robots
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/robot.rb
class Robot < ApplicationRecord
end

app/models/weapon.rb
class Weapon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
	before_action :current_robot, only: [:show, :edit, :update, :destroy]
	
  
  def index
    @robots = Robot.all
  end

  def show
    @robot = Robot.find(params[:id])
  end

  def new
    @robot = Robot.new
  end

  def create
    @robot = Robot.create(robot_params)
    redirect_to robot_path(@robot)
  end

  def edit
    @robot = Robot.find(params[:id])
  end

  def update
    @robot = Robot.find(params[:id])
    @robot.update(robot_params)

    redirect_to robot_path(@robot)
  end

  def destroy
    @robot = Robot.find(params[:id])
    @robot.destroy

    redirect_to robots_path
  end

	def current_robot
	    @robot = Robot.find(params[:id])
	  end


private
  def robot_params
    params.require(:robot).permit(:name, :slogan, :active_status, :weapon)
  end
end
  
  

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/robot_helper.rb
module RobotHelper
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DindaBotApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/robots/edit.html.erb
<h1>Robot#edit</h1>
<%= form_for @robot do |f| %>
  <p>Enter Robot's New Name: <%= f.text_field :name %></p>
  <p>Enter New Favorite Phrase: <%= f.text_field :slogan %></p>
  
  <%= f.submit %>
<% end %>

app/views/robots/index.html.erb
<h1>Robot#index</h1>
<table>
  <% @robots.each do |robot| %>
    <tr>
      <td><%= link_to robot.name, robot_path(robot) %></td>
      <td><%= button_to 'Edit', edit_robot_path(robot), method: 'get'%></td>
      <td><%= button_to 'Remove', robot_path(robot), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to "Add a New Robot", new_robot_path %>

app/views/robots/new.html.erb
<h1>Robot#new</h1>
<%= form_for @robot do |f| %>
  <p>Enter Robot's Name: <%= f.text_field :name, placeholder: "robot name" %></p>
  <p>Enter Favorite Phrase: <%= f.text_field :slogan, placeholder: "robot says.." %></p>
  <%= f.submit %>
<% end %>

app/views/robots/show.html.erb
<h1>Robot#show</h1>

<h2>NAME: <%= @robot.name %></h2>
<h4>SLOGAN: "<%= @robot.slogan %>"</h4>
<h4>Active_status "<%= @robot.active_status %>"</h4>
<h4>weapon "<%= @robot.weapon %>"</h4>


<%= button_to "All Robots", robots_path, method: :get %>

app/views/weapons/index.html.erb
<h1>index weapon</h1>